### ISSUE TITLE
Screenshots!

### ISSUE THREAD

**Issue by danielbachhuber** [helen/wp-media-grid-view#1]
So we can see the lovely.

**Comment by shaunandrews** [comment]
Here's a few of the existing plugin, showing how the slider can change the grid size:

![screen shot 2014-04-19 at 12 12 16 am](https://cloud.githubusercontent.com/assets/191598/2747633/de58e31a-c778-11e3-8197-a168e340c65b.png)
![screen shot 2014-04-19 at 12 12 29 am](https://cloud.githubusercontent.com/assets/191598/2747634/de5ab7c6-c778-11e3-80ec-2e73bb8fbc90.png)
![screen shot 2014-04-19 at 12 12 23 am](https://cloud.githubusercontent.com/assets/191598/2747635/de704b4a-c778-11e3-8861-924bb10d81f4.png)
