### ISSUE TITLE
Use WP Media Backbone code

### ISSUE THREAD

**Issue by ericandrewlewis** [helen/wp-media-grid-view#10]
With some tubular assistance from @staylor, we've got a working prototype using the Media Backbone stuffs on the Media page. It requires a [core patch](https://gist.github.com/ericandrewlewis/11301019), as it requires futzing with some low-level Backbone internals to make the container not the default modal.

Like I said, just a prototype, a lot more work will need to go into this.

**Comment by Mamaduka** [comment]
@ericandrewlewis Is there a ticket for this patch?

**Comment by ericandrewlewis** [comment]
@Mamaduka there's no core ticket if that's what you mean. 

I'm going to be working in the [Backbone branch](https://github.com/helenhousandi/wp-media-grid-view/tree/backbone) here until we have something ready to merge.

**Comment by Mamaduka** [comment]
Great.

**Comment by ericandrewlewis** [comment]
I'm closing this as fixed since we've merged the Backbone.js branch into master.
