### ISSUE TITLE
Footer Moves Up When Admin Menu is Taller than Window

### ISSUE THREAD

**Issue by Kelderic** [helen/wp-media-grid-view#15]
When the browser window is shorter than the admin menu, the main WP footer moves away from the bottom of the screen. See screenshot:

![screenshot](https://cloud.githubusercontent.com/assets/1747252/3001158/8107727a-dd2c-11e3-89dd-a297048e1c82.png)

Reason:
# wpfooter is set to positiion:absolute, and should be position:fixed, only on this page.

**Comment by ericandrewlewis** [comment]
Good catch man, fixed in 2682aff3f367c7eb20c6034d3b4965e06465c6d8
